config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      get "homes/top"
      resources :post_sakes, only: [:index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users, only: [:index, :show, :destroy, :edit, :update]
    end

  scope module: :public do
      resources :post_sakes, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users
      post "users/guest_sign_in", to: "users#guest_sign_in"

      # 退会確認画面
      get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      # 論理削除用のルーティング
      patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"
    end
  get "homes/top"

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @post_sakes = PostSake.all
  end

  private
    # ストロングパラメータ
    def post_sake_params
      params.require(:post_sake).permit(:sake, :comment, :image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @post_sakes = PostSake.page(params[:page]) #kaminariでのページネーション
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container px-4 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
      <div class="m-4">
        <h3>SAKE-Niigata</h3>
        <p>SAKE-Niigataは新潟の特産品である日本酒のレビューサイトです<br>
        あなたが飲んだ日本酒のレビューをしましょう！</p>
      </div>
    </div>
  </div>
 </div>

app/views/homes/top.html.erb
<div class="container px-4 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <% if user_signed_in? %>
      <div>
       <%= link_to new_post_sake_path, class: "btn btn-info btn-sm btn-block  mt-1" do %>
        <i class="fas fa-pen"></i>日本酒を評価する
       <% end %>
      </div>
　　　<% end %>
　　　 <div>
       <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block  mt-1 sign_in", method: :post %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="m-4">
        <h4>ようこそ、SAKE-Niigataへ!</h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
      <h2 class="my-4"><strong>レビュー</strong></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
      <div class="row">
        <%= render 'public/post_sakes/index', post_sakes: @post_sakes %>
      </div>
    </div>
  </div>
</div>