config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
      get "homes/top"
      resources :post_sakes, only: [:index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users, only: [:index, :show, :destroy, :edit, :update]
    end

  scope module: :public do
      resources :post_sakes, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
      resources :users
      post "users/guest_sign_in", to: "users#guest_sign_in"

      # 退会確認画面
      get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
      # 論理削除用のルーティング
      patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"
    end
  get "homes/top"

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_sakes, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @post_sakes = @user.post_sakes
  end

  private
    # ストロングパラメータ
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class ="container my-4">
  <div class ="row my-4">
    <div class ="col-md-5">
      <h2>ユーザー一覧</h2>
    </div>
  </div>
  <div class ="row my-4">
    <div class ="col-md-12">
      <table class ="table">
        <tr>
          <td>会員ID</td>
          <td>名前</td>
          <td>メールアドレス</td>
          <td>会員ステータス</td>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <th><%= user.id %></th>
            <th><%= link_to user.name, admin_user_path(user.id) %></th>
            <th><%= user.email %></th>
            <th>
              <% if user.is_deleted == false %>
					        有効
					    <% else %>
					        退会
					    <% end %>
            </th>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3><%= @user.name %></h3>
    <%= image_tag @user.get_profile_image(100,100), class: "img-fluid rounded-circle" %>
    <% if @user == current_user %>
      <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-primary" %></p>
    <% end %>
  </div>
 </div>
<div class="row">
  <div class="col-md-8">
    <% @post_sakes.each do |post_sake| %>
      <div class="card mb-3" style="width: 15rem;">
        <div class="card-body">
          <%= link_to post_sake_path(post_sake.id) do %>
            <%= image_tag post_sake.image, class: "card-img-top img-fluid"  %>
          <% end %>
          <div class="card-text">
            <p>投稿ユーザー画像：<%= image_tag post_sake.user.get_profile_image(50,50), class: "rounded-circle mr-2" %><%= post_sake.user.name %></p>
            <p>日本酒名：<%= post_sake.sake %></p>
            <p>レビュー：<%= post_sake.comment %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>